### ISSUE TITLE
balena wifi-connect with Debian version: 12 (bookworm)

### ISSUE THREAD

**Issue by hp3icc** [chrisys/chrisys#1]
Hello, could you help me with a report, balena wifi-connect installation script does not work on new raspberry os : 

Debian version: 12 (bookworm)
Release date: October 10th 2023

On Debian 11 it works very well, but on Debian 12 it does not pass the operating system verification and does not install

**Comment by chrisys** [comment]
Hey @hp3icc the repo for wifi-connect is here: https://github.com/balena-os/wifi-connect
